### ISSUE TITLE
FID of the VQVAE

### ISSUE THREAD

**Issue by whwjdqls** [exitudio/MMM#25]
hi great work!

I evaluated the provided vqvae trained on humanml3d and got better results on FID than the ones on the paper and on the logs in the issues. Is this expected?
![image](https://github.com/user-attachments/assets/b538b647-768c-4a23-b2af-18c60efffc58)

**Comment by exitudio** [comment]
Hi,
the first stage evaluation doesn't always transfer to the 2nd stage. It's better to train and evaluate with 2nd stage.

**Comment by wjxxyz** [comment]
> Hi, the first stage evaluation doesn't always transfer to the 2nd stage. It's better to train and evaluate with 2nd stage.

Could you please make public the VQ-VAE model and transformer model related to the KIT-ML dataset?
