### ISSUE TITLE
Could you release the code about motion editing in the paper?

### ISSUE THREAD

**Issue by cuijh26** [exitudio/MMM#4]

**Comment by exitudio** [comment]
Hi,
I added editing code in [edit.ipynb](https://github.com/exitudio/MMM/blob/main/edit.ipynb). Also added pretrain model for upper body editing in [googledrive](https://drive.google.com/drive/u/1/folders/19qRMMk0mQyA7wyeWU4oZNSFkI6tLxGPN)

**Comment by cuijh26** [comment]
thank you
